Update jenkinsfile

diff --git a/CreateCluster_DeployApp/jenkinsfile b/CreateCluster_DeployApp/jenkinsfile
--- a/CreateCluster_DeployApp/jenkinsfile
+++ b/CreateCluster_DeployApp/jenkinsfile
@@ -12,9 +12,12 @@ pipeline {
         stage('Install Tools') {
             steps {
                 sh '''
+                    # Clean up previous installations if they exist
+                    rm -rf awscliv2.zip aws kubectl eksctl $HOME/.local/bin/aws $HOME/.local/bin/kubectl $HOME/.local/bin/eksctl
+                    
                     # Install AWS CLI
                     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-                    unzip awscliv2.zip
+                    unzip -o awscliv2.zip
                     ./aws/install -i $HOME/.local/aws-cli -b $HOME/.local/bin
                     
                     # Install kubectl
@@ -24,11 +27,15 @@ pipeline {
                     mv kubectl $HOME/.local/bin/
 
                     # Install eksctl
-                    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C $HOME/.local/bin
+                    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
+                    mv /tmp/eksctl $HOME/.local/bin/
 
                     # Verify installations
+                    echo "AWS CLI version:"
                     aws --version
+                    echo "kubectl version:"
                     kubectl version --client
+                    echo "eksctl version:"
                     eksctl version
                 '''
             }
@@ -62,14 +69,13 @@ pipeline {
         
         stage('Create Namespace') {
             steps {
-                sh "kubectl create namespace ${NAMESPACE}"
+                sh "kubectl create namespace ${NAMESPACE} || true"
             }
         }
         
         stage('Deploy Hello World App') {
             steps {
                 script {
-                    // Create deployment YAML
                     def deploymentYaml = """
 apiVersion: apps/v1
 kind: Deployment
@@ -108,7 +114,6 @@ spec:
 """
                     writeFile file: 'hello-world-deployment.yaml', text: deploymentYaml
                     
-                    // Apply the deployment
                     sh "kubectl apply -f hello-world-deployment.yaml"
                 }
             }
@@ -117,13 +122,10 @@ spec:
         stage('Retrieve Application URL') {
             steps {
                 script {
-                    // Wait for the deployment to be available
                     sh "kubectl wait --for=condition=available --timeout=300s deployment/hello-world -n ${NAMESPACE}"
                     
-                    // Wait for the LoadBalancer to get an external IP
                     sh "kubectl wait --for=jsonpath='{.status.loadBalancer.ingress[0].hostname}' --timeout=300s service/hello-world-service -n ${NAMESPACE}"
                     
-                    // Get the LoadBalancer URL
                     def loadBalancerUrl = sh(
                         script: "kubectl get service hello-world-service -n ${NAMESPACE} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'",
                         returnStdout: true
@@ -143,8 +145,7 @@ spec:
     post {
         always {
             echo 'Cleaning up...'
-            // You might want to add cleanup steps here, like deleting the EKS cluster
-            // Be cautious with cleanup in production environments
+            // Add cleanup steps if necessary
         }
     }
 }
