Update jenkinsfile

diff --git a/CreateCluster_DeployApp/jenkinsfile b/CreateCluster_DeployApp/jenkinsfile
--- a/CreateCluster_DeployApp/jenkinsfile
+++ b/CreateCluster_DeployApp/jenkinsfile
@@ -9,23 +9,32 @@ pipeline {
                 checkout scm
             }
         }
+
         stage('Configure and Verify AWS CLI') {
             steps {
                 withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'awscredss', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
-                    sh '''
-                    # Display truncated AWS Access Key and Secret Key
-                    echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID}"
-                    echo "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY}"
-                    
-                    # Configure AWS CLI
-                    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-                    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-                    aws configure set default.region $AWS_DEFAULT_REGION
-                    
-                    # Verify AWS configuration
-                    aws configure list
-                    aws sts get-caller-identity
-                    '''
+                    script {
+                        // Adding script block for better handling
+                        sh '''
+                        echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID}..."
+                        echo "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY}..."
+
+                        # Check if the credentials are set
+                        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+                            echo "ERROR: AWS credentials are not set."
+                            exit 1
+                        fi
+
+                        # Configure AWS CLI
+                        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+                        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+                        aws configure set default.region $AWS_DEFAULT_REGION
+                        aws configure list
+
+                        # Verify AWS CLI configuration
+                        aws sts get-caller-identity
+                        '''
+                    }
                 }
             }
         }
